import 'package:fast_immutable_collections/fast_immutable_collections.dart';
import 'package:hypotheek_berekeningen/inkomen/gegevens/inkomen.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'inkomen_bewerken_view_state.freezed.dart';

//flutter pub run build_runner build

@freezed
class InkomenBewerkenViewState with _$InkomenBewerkenViewState {
  const factory InkomenBewerkenViewState({
    required Inkomen inkomen,
    required bool pensioenKeuze,
    required IList<Inkomen> lijst,
    required DateTime origineleDatum,
    required DateTime blokDatum,
  }) = _InkomenBewerkenViewState;
}
