import 'package:fast_immutable_collections/fast_immutable_collections.dart';

import '../../../model/nl/inkomen/inkomen.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'inkomen_bewerken.freezed.dart';

//flutter pub run build_runner build

@freezed
class InkomenBewerken with _$InkomenBewerken {
  const factory InkomenBewerken({
    required Inkomen inkomen,
    required bool pensioenKeuze,
    required IList<Inkomen> lijst,
    required DateTime origineleDatum,
    required DateTime blokDatum,
  }) = _InkomenBewerken;
}
