import 'package:fast_immutable_collections/fast_immutable_collections.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'norm.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'norm.g.dart';

@freezed
class Norm with _$Norm {
  const factory Norm.normInkomen({
    required String omschrijving,
    @Default(0.0) double totaal,
    @Default(0.0) double resterend,
    @Default(false) toepassen,
    @Default(IMapConst({})) parameters,
    @Default(IListConst([])) bericht,
    @Default(0) int periode,
  }) = NormInkomen;

  const factory Norm.normWoningwaarde(
      {required String omschrijving,
      @Default(0.0) double totaal,
      @Default(0.0) double verduurzaam,
      @Default(0.0) double resterend,
      @Default(false) toepassen,
      @Default(IMapConst({})) parameters,
      @Default(IListConst([])) bericht}) = NormWoningwaarde;

  const factory Norm.normNhg(
      {required String omschrijving,
      @Default(0.0) double totaal,
      @Default(0.0) double verduurzaam,
      @Default(0.0) double resterend,
      @Default(false) toepassen,
      @Default(IMapConst({})) parameters,
      @Default(IListConst([])) bericht}) = NormNhg;

  factory Norm.fromJson(Map<String, Object?> json) => _$NormFromJson(json);
}
